### ISSUE TITLE
check_lastest_version doesn't work on arm macs

### ISSUE THREAD

**Issue by prabirshrestha** [nathanbabcock/ffmpeg-sidecar#23]
Seems like latest version still has check for x86_64 targets.

https://github.com/nathanbabcock/ffmpeg-sidecar/blob/c4dff09800dcbe503eca99a01a0272380c99d31d/src/download.rs#L19-L23

**Comment by nathanbabcock** [comment]
Hi there, you are correct, and the reason `check_latest_version` doesn't work for ARM is because the website we use as a source (https://www.osxexperts.net/) does not list a simple text endpoint that displays the latest version number. Short of scraping and parsing the HTML of the webpage there is no easy way of determining it. The other providers have something very convenient [like this](https://www.gyan.dev/ffmpeg/builds/release-version). (Unless you happen to know of an endpoint I am overlooking).

I'll change this function to return the same version number as what would be provided by the `ffmpeg_download_url` function (which also has to be manually updated).

I just updated the CI pipelines for Mac M1 in this PR: https://github.com/nathanbabcock/ffmpeg-sidecar/pull/37. So everything appears to be in working order. In the future I might want to revisit  this whole auto download functionality (and #19) as it's proving to be very brittle over time.
