### ISSUE TITLE
Error: Unrecognized option 'filtergraph'

### ISSUE THREAD

**Issue by samrat** [nathanbabcock/ffmpeg-sidecar#26]
Hello,

I'm passing a `filter_complex` argument, which seems to get translated into `-filtergraph` when the ffmpeg CLI is invoked: https://github.com/nathanbabcock/ffmpeg-sidecar/blob/ee2e4c0530a8480da7a0f53a574dd9b9abb63346/src/command.rs#L469

However, for version 6.0, this flag doesn't seem to exist. I also couldn't find any docs for older versions pointing to this flag. 

Was this a typo?

**Comment by nathanbabcock** [comment]
Hello!

Great catch. I wish I could tell you this was an older alias of the command from before FFmpeg v6.0...but I can't find any evidence that it is. I even went back to some of my older projects that were using `ffmpeg-sidecar` in combination with filter graphs — in those, I used `.arg("-filter:v")` (another valid alias) instead of this particular preset method. Looks like it really was just a typo!

Thanks for noticing this and making the PR to fix it. I will merge that today, and publish a new crate version early this week: v1.0.1.
