### ISSUE TITLE
Download fails due to sidecar path under restricted system directories

### ISSUE THREAD

**Issue by clytras** [nathanbabcock/ffmpeg-sidecar#43]
In a case when the app is living inside a restricted directory, like `C:\Program Files` on Windows, the `download_ffmpeg_package` fails with the error `Failed to download ffmpeg`. I believe this happens because `curl` does not have elevated access to write inside program files, thus it fails with that error internally.

I think the best approach to such issues, is to allow changing the default sidecar directory location to an unprivileged path.
Is there a way to change the default sidecard directory?

**Comment by nathanbabcock** [comment]
I'll have to think about a better way to handle this situation automatically, but the short answer is yes, you can customize the sidecar directory pretty easily. Instead of using the `auto_download()` function directly, you should copy and paste the few lines inside it and customize your desired paths:

```rs
  let download_url = ffmpeg_download_url()?;
  let destination = sidecar_dir()?;
  let archive_path = download_ffmpeg_package(download_url, &destination)?;
  unpack_ffmpeg(&archive_path, &destination)?;
```

You can also deconstruct the [`download_ffmpeg`](https://github.com/nathanbabcock/ffmpeg-sidecar/blob/main/examples/download_ffmpeg.rs) example to accomplish the same thing.

**Comment by clytras** [comment]
And how the rest of the ecosystem will know about that changed sidecar directory to go and look for the binaries?

I mean, the `ffmpeg_path` uses the `sidecar_path` which it uses the `current_exe` path, so, if I download the binaries to a sidecar path that is not in the system PATH, how it will know about that custom sidecarr path? Will it work then?

I'll try this out and see if it works.

**Comment by nathanbabcock** [comment]
You're right that the other methods will not automatically know to look in a nonstandard place, so you will need to use variants such as `FfmpegCommand::new_with_path()`, `ffmpeg_version_with_path()`, `ffprobe_version_with_path()`, etc.

Another option would be to add `ffmpeg` to the system path after downloading it using some third party crate. Rather than having the library do something like that automatically, I'd leave that up to each application on a case-by-case basis.

**Comment by clytras** [comment]
I didn't see such functions and methods exist! That will work perfectly, thank you 💪
