### ISSUE TITLE
Is using curl to download ffmpeg going to be consistent over all platforms ?

### ISSUE THREAD

**Issue by VirtualPirate** [nathanbabcock/ffmpeg-sidecar#47]
I happen to use `ffmpeg-sidecar` for a desktop application in tauri.

And I happen to download the `ffmpeg` binaries during runtime of the desktop application, which seems to work great ...

Now, the concern is, It might not be guaranteed for `curl` to exist on every platform that the library is running on. Wouldn't it be nice to use native http library in rust to download the ffmpeg files, to remove the external dependency the library has on curl .

**Comment by nathanbabcock** [comment]
Hi @VirtualPirate, thanks for mentioning this. I totally agree with your reasoning. These hidden external dependencies are a potential failure point that I'd like to eliminate to make the library more robust as it gains more users. It would also allow for other requested features like showing progress during download (#44). I'd like to:

- Replace `curl` with [`reqwest`](https://docs.rs/reqwest/latest/reqwest/). It's the most widely-used Rust HTTP client and still pretty lightweight.
- Introduce an optional crate feature such as `download_ffmpeg`, enabled by default, so users can choose to opt out of the `reqwest` dependency if they don't want it.
- Replace a second hidden dependency -- the `tar` command used to unzip downloaded archives -- with another lightweight native Rust lib.
- Keep the external-facing API backwards-compatible (with different implementation details underneath) so that this is a minor version change with an easy upgrade path

If anyone is interested in opening an initial PR for this I'd be happy to help review and get it merged. Otherwise I will begin work on it sometime in the near future.

**Comment by VirtualPirate** [comment]
#48
