### ISSUE TITLE
Failed to download ffmpeg

### ISSUE THREAD

**Issue by bliongosari1** [nathanbabcock/ffmpeg-sidecar#52]
Any ideas how to deal with this? Happening on some windows computer

Seem to fail here 
<img width="678" alt="Screenshot 2024-10-18 at 3 53 03 PM" src="https://github.com/user-attachments/assets/7509195e-ce7f-42dc-b658-3de7e6e28368">

windows 10.0.19045 also one with 10.0.22631
happening for one of my users even after multiple retries

**Comment by nathanbabcock** [comment]
Hi @bliongosari1, first off could you try updating your dependency version to `ffmpeg-sidecar = "1.2.0"`?

In a recent PR we changed the download functionality from `curl` to `reqwest`, since not all computers may have `curl` installed natively. This might fix your problem right away — but if not, it should also provide more detailed error logs about which part of the process failed (HTTP status code, problem while unzipping archive, etc.)

**Comment by bliongosari1** [comment]
FYI @nathanbabcock I tried with my Windows VM and it gave this error with the reqwest

Failed to read response bytes

**Comment by nathanbabcock** [comment]
Huh, that's weird. I tried it just now on Windows 11 and it worked for me.

I assume that if you manually click the link to the Windows release in your browser, it will download the zip just fine, right?

https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-essentials.zip

**Comment by nathanbabcock** [comment]
I can't repro, please re-open if you're still having problems with this.
